### PR TITLE
Fix compaction with holes

### LINKED ISSUE #36: Little bug when compacting with tombstones
When the first Sstable has 0 records, it prevent the compaction of all the tombstone of other sstable.

The first sstable is never selected for compaction. How can a sstable have 0 records ? Should it still exist ?

### PR DESCRIPTION
**Pull request by thomasjungblut**
This change updates the file selection process to include files regardless whether the sizes fit. This fixes a longer standing issue where smaller files between larger files (e.g. due to tombstone removal) can cause the data lineage to be corrupted.

This adds more tests and bumps the go version to 1.23.

fixes #36

cc @sebheitzmann  in case you want to test drive this a bit

### CODE REVIEW

**Comment by sebheitzmann** [comment]
I will check that, no pb.

File: simpledb/sstable_manager.go [hunk 1]
```diff
@@ -117,28 +116,67 @@ func (s *SSTableManager) candidateTablesForCompaction(compactionMaxSizeBytes uin
...
+			- Table 1 (size 2gig)
+			- Table 2 (size 1gig)
+			- Table 3 (size 3gig)
+			- Table 4 (size 1gig)
+
+		Given maxSize=2gig, the above selection would select table 2 and 4 as candidates.
+		Which will create an entirely wrong data lineage, as the changes from Table 3 will be completely ignored and an
+		entire new Table 2 will be created with "changes from the future".
+
+		The below function will fill the holes, by also selecting the tables in between for compaction - so the lineage is always preserved.
```
Comment (sebheitzmann) [inline simpledb/sstable_manager.go:135]: even if you add the table 2,3 and 4 this selection prevent sending the tombstone to the first table. This make the physical deletion of the data in table 1 impossible. The database will grow indefinitely without any possibility to shrink. I think that size selection is incompatible with the possibility of shrinking. The only case when size selection is possible is when the sstable contains no tombstone.

**Review by sebheitzmann — COMMENTED** [review]
The rest of you PR seems correct for me.

File: simpledb/sstable_manager.go (hunk 1 above)
Comment (sebheitzmann) [reply simpledb/sstable_manager.go:135]: https://github.com/thomasjungblut/go-sstables/issues/36#issuecomment-2480501544

I think that this note is still actual. What about a separate Garbage collection process ?

**Comment by thomasjungblut** [comment]
they will stay as long as they are over the threshold. I'm thinking about
adding a tombstone counter to the sstables metadata and then we can also
select them based on how much space is wasted in them.

File: simpledb/compaction_test.go [hunk 2]
```diff
@@ -142,3 +143,81 @@ func TestExecCompactionWithTombstoneRewriten(t *testing.T) {
 	// check size of compacted sstable
 	assert.Equal(t, 1000, int(db.sstableManager.currentSSTable().MetaData().NumRecords))
 }
+
+// regression reported in https://github.com/thomasjungblut/go-sstables/issues/36
+// more specifically this relates to a case where the first table is above the compaction threshold and never compacted.
+// The keyspace might already be partially rewritten, thus wasting unnecessary space.
+// This test is supposed to fail for later changes, thus the assertion is inverted
+func TestCompactionWithTombstonesBeyondMaxSize(t *testing.T) {
```
Comment (thomasjungblut) [inline simpledb/compaction_test.go:151]: @sebheitzmann I've added a regression test for this now - I hope this is the actual case you're referring to
